version: '3'

networks:
  tailscale_proxy_example:
    external: false

volumes:
  tailscale-whoami-state:

services:

  whoami:
    image: traefik/whoami
    networks:
     - tailscale_proxy_example

  tailscale-whoami-proxy:
    image: hollie/tailscale-caddy-proxy:latest
    volumes:
      - tailscale-whoami-state:/var/lib/tailscale # Persist the tailscale state directory
    environment:
      - TS_HOSTNAME=tailscale-example 		  # Hostname you want this instance to have on the tailscale network
      - TS_TAILNET=tailnet-XXXX         	  # Your tailnet name without the .ts.net suffix!
      - CADDY_TARGET=whoami:80			  # Target service and port
    restart: on-failure
    init: true
    networks:
     - tailscale_proxy_example
